rg_name   = "rg-acajas-dvfinlab"
vnet_name = "vnetacajastfweekly"
subnet_name = "subnet-acajas"
nsg_name = "nsg-acajas"
public_ip_name = "ip-weekly-exercise"
ni_name = "ni-acajas"
lb_name = "lb-acajas"
vm_name = "vm-acajas"